/**
 * Menu-bar icons as template images (macOS tints them for a light or dark
 * menu bar). Both share one 30×22pt canvas so swapping never shifts the
 * menu bar: `normal` is the envelope alone, `selected` adds the translucent
 * pill macOS draws behind a status item whose menu is open. Glaze's Tray has
 * no highlight API, so the popover's open state swaps these instead.
 * Rendered once from the SF Symbol `envelope.fill` (14pt) with AppKit; 1x + 2x PNGs.
 */

import { nativeImage, type NativeImage } from "@glaze/core/backend";

const PNG = {
  normal1x:
    "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAWCAYAAADXYyzPAAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAAHqADAAQAAAABAAAAFgAAAADZ+V7+AAABRElEQVRIDe3UvUsDMRjH8YquugiiSEGHQp26OXTRQZwLDi7i1FHoXjq2FPofOLV1cioICuoourg4iIMgRZzcdLD4/vL9wQVCwaTG63YPfLhc8iTPJQ1NpZJITmBIJzDiWXeC8TamPHn28AcvLTTtzr+2l5mwhld8D+iEvBksIjjemLmBVfTgK35AjoqeoorgUKEvbCGPB/xWfJexWVxEOTWewWEXqbBKDvew+9XexhyuYcZiK6wF68jgFqZAg/Y87qw+jTkLj5EwaHySeA7d8CXsYB9HeEYXacQSZlf6nTdRwDv2kMU6HnGGaejDzBznjslzhllEl2sFLzB9/c9jxnSjL6Ocfxcus5Bu9FO0YH9B+71Djo77Bs7CoyS4Qjs8hHajfzFfLJAwiSK09hWCYpxZ+np7V7627kMpqFoyKTmBOE7gB2kDfe9P+NwDAAAAAElFTkSuQmCC",
  normal2x:
    "iVBORw0KGgoAAAANSUhEUgAAADwAAAAsCAYAAAA5KtvpAAAAAXNSR0IArs4c6QAAAGxlWElmTU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAACQAAAAAQAAAJAAAAABAAKgAgAEAAAAAQAAADygAwAEAAAAAQAAACwAAAAAgRWX2AAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAAnlJREFUaAXtlz1rVUEQhpNI8AMU/EilEEIsLAWjCIKlTRrBwmCRIohVCgsbk0pNbEQRxB+gQhQURCy1EYJfICQIImJnoWgj0aioSXzesAPLcnNy5ebs3WIGnszunt2deWfPOfeko8PNK+AV8Ap4BbwCXgGvgFegngp0trBtF2uPwH7YDK3sxfJKW+LqHLyER6B+dttDxI+g4Ln4QKx+yG6bQsRe/BvIIXiWODtDXIsfuvW7GUIcCmG24p9AnaIfs/+WEO8w/lVoZ3MLRPoJx0LE9fg7UIfom+zbHeIcx/8KhKE8zoRJ+OkQUi+tS2DX1sJPhr3lzsAiaN8/kNVSMVeIrre2bBRUiHTO//T/sv4UyLTvNYjXt12wkrkLG0B2FH5AnGSz7e+sGwTZRrgP6doiBCupadgGsoPwBdJkq/qfmD8Ash3wDBrNL0awknsLfSDbDe+hUdLpWLxOv7XvKtYVJVhC4pPqof+8InnN152xHWQH4DOkBYn7xQlWcnoW94JMHwoPIE7a2vcYt2d/H+35FebZfPkiBd8iMXtz01xuX8fHiV9N5qyjfzuZE8+3dnGC9bFgYs/Rvgj6nZaNwEMYVgfT+GU4qw7WjOiiBMdizyPATkUnri+y2NSPT7RZ0cUIXkmsidY/AEOgZ/sEvAa7Zn6MMVnVSRcheDWxJqgZH4ueQny6pu2C11KsiasS3VbBdYhdTXTbBMdiLzS49SzxVvy4HmhMz7Td3r+XRzL++UqsG9AVYtYl1gqVitaXWFY7SbRcYhuJHsmqNgo2QdsSyuHtpKMU8jX7CPUCvkEOsYrzFHaBm1fAK+AV8Ap4BbwCXgGvQHEV+Afy/GNGT6P27QAAAABJRU5ErkJggg==",
  selected1x:
    "iVBORw0KGgoAAAANSUhEUgAAAB4AAAAWCAYAAADXYyzPAAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAAHqADAAQAAAABAAAAFgAAAADZ+V7+AAAB2UlEQVRIDb2WyytEURzHZwxpIlKaKCSRR1jJzs7fIiwsvMqCUohEkdde9gplYY2llRJl5dGQpCmMZvh8pzk1j/tCc7/1ueee8/ud87vnnN+59wYD2YpQFWEIZZv+XEvQ8x2iaVIDBVPXQKCEsgUq0vVCFW8MfA1fZlZtVAodVJMphXJ4UmAtbQ34JQWPF3FRYL8VKSaiEslOZRhmoMrOwaJdyXQEhxY20xRWYLPPpjGzbKVyDLOgBPSiC5zOoQMubTqEtNROWsOoPZmADyfHtO2UchrmoS/dZlm4BdaKaKnrYQRiYKcTDIuwCt1gjiq3+XILrB4aYAx6YBheIFf7NGzBBuh94Covgc0gA9z0wyA8mkbKPdiFbWgAT/pN4CQjKlmU4UOgJNIMlXyfcA+epT30om+c5kClllRJpP3UsmqmtzAFy9AOrvIaWAnzDCug46eMzczaLupKwknQSWgCR3lZ6h1GuIIlKHEYrRfbOIzCnYNfyqSnr3NwimM7g3XQW8xNjThUwgJoUtoCSylwLdjN/AbbJlSDVzXj+AAHDh0SOqOdoE+Vn4pppvoz8FtRE1h/Bn5JsaLaY+kVtNz6IBRSCqpfn2TuizxCo9A32jwUt/9Sgt55P3s/j6hNnLsjr7AAAAAASUVORK5CYII=",
  selected2x:
    "iVBORw0KGgoAAAANSUhEUgAAADwAAAAsCAYAAAA5KtvpAAAAAXNSR0IArs4c6QAAAGxlWElmTU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAIdpAAQAAAABAAAATgAAAAAAAACQAAAAAQAAAJAAAAABAAKgAgAEAAAAAQAAADygAwAEAAAAAQAAACwAAAAAgRWX2AAAAAlwSFlzAAAWJQAAFiUBSVIk8AAABB1JREFUaAXdmstLVFEAxsfHmLQILY0yCzIDk4gW1SaIioL+gKCgRRT2flCbKLAYTGpRqx4g1UKDFkFBi6BNERZtIiiidwYWGlGRRorlo/p9M/cMV5vrOGfuzfF+8Jtz59zz+u55ztW8yOgq4napQzFhFAoglzREYwbgJ3Q59BOmVF7K2EhERiuhHLzSeGQd9+g/tOALdMA/xlOZUY9WQ671JE3KSOr5NlCvJzXS1AzuyGx+MsXEvZCHMhiEHmPDbdj0rLkXlrAEI72gOZ7sSc1Z9WxYJW/ymDSsBcrd27oXJsmbPMYNy7lW47BLHos0sTV3U63WYXsA8lhqDIfNnJef0kLu6ARlIz2sZVALk20KyDCPVtoX8BB0uLBRsQzruGij2WSqh2k2mS3zfCbfbui0zB9VL9mszhoV76EO2uF/qI1KVJ/M2o7KAhm20QUyLYJPsB2eQJB6ROE7QWfkxdAEVrI1PI/azsIq+AH74TYEoVsUehA0h9fAGagCK9kaVj7t342wAfTz7BhcAT/VQmENMAibnGutObbtjhSSORup4gOgHx3q8XOgYa4esW4UeX/DKbjhlKPy1kPWyqZR7so38uU4qNevwRH4BTbqI9MhkNlJcBJ8MUs5WfWC8ru1mi/q5SlwD/ZCN2SibyTeAw+gBDRiVoBv8quHTYO0cl+ECngG26ATxqIPJFL6lzALtBMsBF/lt2E1bg7I9ALogDp4DqPpKTe1vX2EWrgEOtj4riAMq5FT4TzMBw1rDe/7kEp3idwH36EGlE/DORAFZViNbYV3Tqv1tuEwXHe+m+AqF/VgXra94drrwZg8WYXZbkteleuw0AjaXjQvVU8TnIZXsBLugNLlgQ4uGgmXIQbS2kTg72cQhkea3eo0eTrhCbjpoOgoHAW3uUBN+23Yy6zMrYNqkKF2mAuboQqMdnGhHm+BGEjuh5GIyeLTT8OjmTVNlOEG88Uj1I8EKRDTfhkei9mEjbF9BmbaD8N+mzWPJBDT2Rp2m9XBYYtprU+hTGtON0MMJM1p21c88e0iXkqGHz2k137ZCNp6gjBLsXHtcMJmwphzvdQJMw4KyFGZca7EqUjHv6DNmqYt4WIIHkMraM/WISVjyfBMyM8w52vSa1jp6fs9jL2a4jZtZZaCh2R0wKuGNPEV3Ndr2r406fy6rXqWgw4wthrQglADgR3WbVsWUL5u9fCwPxgHVFGuFNtlDFsv87niZAztkMe44X4u9L437JLHfrM6d/BFy35YJW/ymPwziyK0CpYpMoR6i6de+dI+bKS3EoMQthW7HU9fIS63YUXoyKgnUQpmuHM5IaVRq55NmpUL7cOpVESkjpzl4JUmVb5ciNNqrAVKc1YL8jClMyPj6m1RDFEYOSqIGlepJ3Va1JRM+6+HfwFhhsXN/4XCCwAAAABJRU5ErkJggg==",
};

/** Matching 1x and 2x artwork, as the Tray docs recommend. */
function icon(png1x: string, png2x: string): NativeImage {
  const image = nativeImage.createEmpty();
  image.addRepresentation({ dataURL: `data:image/png;base64,${png1x}`, scaleFactor: 1 });
  image.addRepresentation({ dataURL: `data:image/png;base64,${png2x}`, scaleFactor: 2 });
  return image;
}

let cache: { normal: NativeImage; selected: NativeImage } | null = null;

export function trayIcons(): { normal: NativeImage; selected: NativeImage } {
  cache ??= {
    normal: icon(PNG.normal1x, PNG.normal2x),
    selected: icon(PNG.selected1x, PNG.selected2x),
  };
  return cache;
}
